### ISSUE TITLE
招募组员

### ISSUE THREAD

**Issue by Wenting11** [Wenting11/Tingting-sing-ancient-prose#1]
（已有1名组员，计划再招1名）   
要求：
行动力执行力强的；  
对「儿童教育&古诗文」感兴趣；   
对产品、策划、色彩、音乐某方面擅长，会制作动画或者视频；  
至少完成3次小作业或1次大作业；  
最好在厦门；  

想了解项目请点击左上角的code

若有兴趣，请在下面留爪印或者添加我的微信（wendy366100）联系，介绍一下你自己，擅长什么，并附上你的仓库链接。

**Comment by JIANG09** [comment]
报名～

- 名字：珊屹
- 坐标：重庆
- 擅长：认真的做事情（不知道这个算不算），认知写作课是学的很认真的，每周的所有作业都完成并修改，喜欢写作，会一直坚持输出～上过第四期，做bp获得了好像是第四名，主要负责文字精简部分。上期上课的时候感觉没有入门，这一期好多了，很多知识点明白多了。
- 项目想法：对儿童教育和古诗文挺感兴趣的，觉得这个idea不错，所以想参与。
- 微信：jiangshanyi0818
- 请问仓库是个人主页吗？如果是的话： [仓库](https://github.com/JIANG09  )
