### ISSUE TITLE
最小故事构想

### ISSUE THREAD

**Issue by Wenting11** [Wenting11/Tingting-sing-ancient-prose#4]
「婷婷唱古文」是真实的项目，不过是别人家的。
起源时，诗歌跟音乐就不可分割，现在婷婷唱古文就是通过唱的方式将诗歌和音乐结合，很美，感兴趣的话可以试听一下。其实他们才发展了一年多，已经迅速崛起了，因为太新颖了，国内没有人这样做。人人（孩子）爱故事，人人（孩子）也爱音乐。孩子很喜欢，号称“背诗神器”，不要被这个称号吓到，只是利用了人类大脑很擅长记忆有旋律的音乐。它更重要的功能是用孩子喜欢的方式进行古诗词启蒙、音乐启蒙。
如果你家有小朋友可以关注婷婷唱古文公众号哦。

先有个最小故事构想，然后迭代。婷婷唱古文公众号「每日一星」里小朋友真实的故事能有一些启发。你们也把最小故事写出来，互相启发。

**Comment by Wenting11** [comment]
**4.0版** 根据十二教练的意见 增加产品功能描述
事件一：
宝儿妈想给宝儿古诗词启蒙，兴致冲冲地给宝儿念诗，但是打脸了，没念完宝儿就跑了。。。他不喜欢，坚持不下来。宝儿妈又找不到合适的方式，这件事也就这么落下了。

事件二：
偶然在喜马拉雅上听到《婷婷唱古文》的一首《江南好》（可以换其他诗歌，视频制作的时候放一段婷婷唱的古文，这一段最好是大家都熟知的古诗，旋律又朗朗上口的），

宝儿妈激动道：对，这就是我想要找的。孩子爱故事，也爱音乐 。音乐与诗歌的结合，太美了！

宝儿妈随即关注了婷婷唱古文公众号，发现了三个功能块：
婷婷唱古文：谱词成曲，每一首古诗的谱曲都源自古诗本身意境；朗朗上口，快乐学古诗。
婷婷诗教：用唱的方式，让孩子趣味学诗，提升孩子的审美与艺术修养，启发孩子们感知生活观察世界，进而自己创作诗词。
多才多艺：诗词音乐一起学，孩子最好的音乐启蒙

事件三：
宝儿喜欢上了唱古文，还喜欢作诗，看到白云，看到落日、看到下雨，都会即兴编上一首打油诗。

雨
染红木槿花
染绿草儿嫩。
入水无处寻，
入林万叶生。

宝儿妈也重拾了对古诗词的爱好。现在宝儿最喜欢的还是和妈妈一起唱，全家人一起斗诗

----
**3.0版**，去掉前面那个出去玩的例子。最朴素的想法是，很多爸爸妈妈想给孩子古诗词启蒙，但是念他不喜欢，很少很少能坚持下来。
事件一：给孩子念诗，他不喜欢
事件二：偶然听到婷婷唱古文，旋律太好了，这种诗歌和音乐结合的方式很棒
事件三：尝试放给孩子听，孩子也喜欢上。

宝儿妈想给宝儿古诗词启蒙，兴致冲冲地给宝儿念诗，但是，没念完他就跑了。。。他不喜欢，坚持不下来，又找不到合适的方式。

偶然在喜马拉雅上听到《婷婷唱古文》的一首《江城子》（可以换其他诗歌，视频制作的时候放一段婷婷唱的古文，这一段最好是大家都熟知的古诗，旋律又朗朗上口的），

宝儿妈激动道：对，这就是我想要找的。孩子爱故事，孩子也爱音乐 。音乐与诗歌的结合，太美了！

宝儿喜欢上了唱古文，还喜欢作诗，看到白云，看到落日、看到下雨，都会即兴编上一首打油诗。

雨
染红木槿花
染绿草儿嫩。
入水无处寻，
入林万叶生。

全家人也喜欢上了婷婷唱古文，他最喜欢的还是和妈妈一起唱，全家人一起斗诗

-----
20171220
我小结一下我的思考：唱这一点，可以体现在妈妈在听到的那一刻，这时候音乐出来（**音乐出来能给人很具象的感受，比我们说百遍唱有感觉**）。然后妈妈说这就是她想要找的。

而且这个痛点，我觉得一定要宝儿妈（家长）感受到。我们面向的用户是家长，孩子是使用者，但是决定者挑选者是爸爸妈妈。所以我想了想可能还是不适合宝宝和小姐姐的对比，除非这个对比戳痛或者触动了妈妈

我2.0版的问题我个人觉得在于前面那个出去玩，孩子感觉和表达很单一怎么引到古诗词启蒙上去。或者不需要前面出去玩那个例子。一般做父母的都会想给孩子古诗词启蒙。以及文字还没有修改润滑，显得很生硬。

----
大家可以提修改意见或者写出最小故事

分析：我们的bp和二期「陪孩子读诗」很像，但是又有很大的不同，我们的是唱古文。
另外他们的用户肖像：文艺青年型的妈妈
我们的**用户肖像：任何想给孩子古诗词启蒙的妈妈**，非文艺的可能更多。以我自己为例，我之前就懵懵懂懂的想给孩子古诗词启蒙，没有想非常多，就觉得古诗词好，自己也很喜欢但不代表水平好。

-----
**2.0版**

宝儿妈和宝儿出去玩，看到一处美景
宝儿妈：真美啊
宝儿：真美啊
宝儿妈：真漂亮
宝儿：真漂亮

宝儿妈：。。。。

宝儿妈郁结了，如果宝儿看到美丽的风景，和她一样只会感慨句「真美啊」，伤心的时候是「好伤心」，这样的情感表达太苍白单调了。宝儿妈希望宝儿能够用「五感」细腻地感知这个世界，希望宝儿的世界颜色似乎有温度，声音似乎有触觉，冷暖似乎有重量。

宝儿妈想到了古诗词，那些堪称感觉博物馆，“月出惊山鸟，时鸣春涧中”（视觉触觉都有）

宝儿妈想给宝儿古诗词启蒙，兴致冲冲地给宝儿念诗，但是，没念完他就跑了。。。他不喜欢，坚持不下来，又找不到合适的方式。

偶然在喜马拉雅上听到《婷婷唱古文》的一首《江城子》（可以换其他诗歌，视频制作的时候放一段婷婷唱的古文，这一段最好是大家都熟知的古诗，旋律又朗朗上口的），

宝儿妈激动道：对，这就是我想要找的。人人爱故事，人人也爱音乐 。音乐与诗歌的结合，太美了！

宝儿喜欢上了唱古文，还喜欢作诗，看到白云，看到落日、看到下雨，都会即兴编上一首打油诗。

雨
染红木槿花
染绿草儿嫩。
入水无处寻，
入林万叶生。

全家人也喜欢上了婷婷唱古文，他最喜欢的还是和妈妈一起唱，全家人一起斗诗


-----

**1.0超级粗略版**：
事件一：
妈妈想给孩子古诗词启蒙，但是没有合适的方式，给孩子念诗他不喜欢，坚持不下来（这个也有真实的案例）。

事件二：
偶然在喜马拉雅上听到《婷婷唱古文》的一首《江城子》（可以换其他诗歌，视频制作的时候可以放一段音乐），感动到。把它作为古诗词启蒙的方式。

事件三：
孩子喜欢上唱古文，喜欢自己编曲，跳舞，还会应景吟诗，还会作诗

**Comment by soniclr** [comment]
1.0版
春暖花开，江心湖畔，莲花朵朵，候鸟翩翩。
美景迷住了宝宝的双眼，他忍不住发出一声赞叹：“好美啊，老铁666”
此时，远处传来一阵孩儿般的轻声吟唱：泉眼无声惜细流，树阴照水爱晴柔。小荷才露尖尖角，早有蜻蜓立上头。
宝宝愣住，有点委屈，妈妈，那小姐姐唱的好美。
忍不住一声轻叹，奈何自己也不大会诗词，何况要教小孩呢。
只见那女娃娃跟随着大人走来，宝宝扑腾扑腾跑过去，姐姐，你唱的好好听，能教教我吗？
两小孩就欢快的去吟唱了。

大人席地而坐，攀谈。言罢，方知，小孩喜欢美妙的旋律，精准的音符，我们大人何尝不是如此呢。

他们向我们展示了《婷婷唱古诗》的节目，不同的古诗词，不同的节奏吟唱而出，朗朗上口，绕梁三日，不绝于耳。

宝宝自此回来后，每日都想听着词，唱着曲儿。 看到大白鹅会唱：鹅鹅鹅，曲项向天歌；吃饭后，会诵读“谁知盘中盘，粒粒皆辛苦”；看着春景图，会低吟“春去花还在，人来鸟不惊”……

家中无时不刻，都陪伴着《婷婷唱古诗》的声音，烟气萦绕，若古声古色……

-----
这个唱古文有几个点，一个是唱，一个是诗词
1. 我们故事里面强调了诗词，但是没有说为什么要唱，有什么好的。 
2. 故事会和陪孩子读诗有点类似
3. 故事性冲击或者升华，感觉上有点硬，不能突出唱古文

**Comment by Wenting11** [comment]
「，兴致冲冲地给宝儿念诗，但是，没念完他就跑了。。。他不喜欢，坚持不下来，又找不到合适的方式。」这个不算吗？还是太简略了？

**Comment by JIANG09** [comment]
## 初稿

故事1 ：宝儿学校举行了歌咏大赛。宝儿献上自己的拿手曲目周杰伦的《双截棍》
“我拿根双截棍，哼哼哈尼～我拿根双截棍，哼哼哈你～”
看着宝儿在台上活蹦乱跳，台下的小朋友们拍手叫好，宝儿妈妈却有点担心。宝儿成天哼的都是这些流行乐曲，有写单调，有些苍白，总觉得缺了些什么。
音乐本来是美好的表达，好的音乐可以是一盏灯，指引人向上，向善，向美。可是，宝儿的音乐世界，却没有这些东西。

该怎么办呢？

故事2一天，宝儿妈妈带宝儿在小区里散步，听到一阵清脆的银铃般的歌声，原来是隔壁梅梅。梅梅银铃般吟唱着：落霞与孤鹜齐飞，秋水共长天一色。（可以换个别的）
宝儿妈先是一愣，唱的好美，歌美，词美，和天地融为一体。然后激动道：对，这就是我想要找的。用音乐，感知古诗词。音乐与诗歌的结合，太美了！

音乐可以是一盏灯，指引宝儿打开文化宝藏，那些堪称绝唱的古文（或古诗词），“青箬笠，绿蓑衣，斜风细雨不须归。”

“梅梅，这是谁教你的？”
“是手机上的婷婷老师，她每天都给我们唱歌！”

晚上，宝儿妈妈打开《婷婷唱古文》听了一首，《木兰辞》。

。。。。。。。。。占位符（还没写好，可以参照陪孩子读诗的对比方法，将流行歌词和古文的文字贴出来，插入音频）

故事3: 宝儿喜欢上了唱古文，还喜欢唱古诗，看到白云，看到落日、看到下雨，都会唱上一首。
全家人也喜欢上了婷婷唱古文，和宝儿一起唱，家里的文化氛围浓浓的。

除夕夜，家里团团圆圆，全家人一起唱《春节谣》，宝儿唱的最开心，我们笑的很开心。（keynote上放上《春节谣》的歌词和音频）

----
## 初稿感想

可以从别的角度切入，我选的是流行音乐和古诗词音乐的对比。因为我们的重点不完全是诗词，学诗，而是唱诗，所以强调音乐对诗词的指引作用会比较有针对性，也不容易和陪孩子读诗重合，音乐是我们的亮点，可以重点突出。

------
1 我觉得这个和陪孩子读书的结构很像，做出来如果不能超越前者，也会被遗忘。你有没有建议从不同的角度来写这个最小故事？
2. 我们的故事是要表现唱诗，这在keynote中怎么体现比较好？有没有类似建议？
3. 和陪孩子读诗有点类似，但是不如他逆转自然，差别在哪里？

**Comment by soniclr** [comment]
keynote 唱的，我的初步想法是，找一张场景图，譬如小孩看到一群白鹭，或者莲花，故事引入“好美”，然后，背景音乐响起“一行白鹭上青天”之类的，不过这个要结合我们的故事来弄比较合适。

看到美景。
我喊了一一噪子：卧槽，真美啊。
你念了一首古诗：落霞与孤鹜齐飞，秋水共长天一色。（原问题误写为“海天共秋水一色”）

感觉这个段子里面，有对比，有冲击，是否可以对我们的故事有点启发。

这只是一个段子，如果按我们故事是为了指向宝妈的话，【我】可以替换为小宝宝，【你】可以替换为左领右舍的孩子之类的，有个对比冲击

**Comment by Wenting11** [comment]
「，兴致冲冲地给宝儿念诗，但是，没念完他就跑了。。。他不喜欢，坚持不下来，又找不到合适的方式。」这个不算强调唱吗？因为念诗给孩子听对孩子来说太枯燥。

我是想在妈妈在喜马拉雅听到比如《江南好》就放江南好的背景音乐。后面还可以放到孩子唱的，婷婷唱古文公众号里也有，看来必须联系人家了。

好多问题。我们想想。
我看了下你们的问题主要是两个：怎样更好地体现唱？；二，怎样逆转更自然或者说觉得故事性不够？

我感觉这两个问题好难啊。

（很有意思！可以修改之前的评论，可以把没说明白的地方补充一下）

**Comment by Wenting11** [comment]
好多问题。我们想想。

**Comment by Wenting11** [comment]
我看了下你们的问题主要是两个：怎样更好地体现唱？；二，怎样逆转更自然或者说觉得故事性不够？

我感觉这两个问题好难啊

**Comment by soniclr** [comment]
婷婷唱古文，为了和陪孩子读诗作差异化，如何从【唱】入手。唱体现音乐，节奏，小宝宝喜欢音乐性，节奏感，能不能从这个来拓展，还没想好

**Comment by soniclr** [comment]
看到美景。
我喊了一一噪子：卧槽，真美啊。

**Comment by soniclr** [comment]
看到美景。
我喊了一一噪子：卧槽，真美啊。
你念了一首古诗：落霞与孤鹜齐飞，秋水共长天一色。（原问题误写为“海天共秋水一色”）

感觉这个段子里面，有对比，有冲击，是否可以对我们的故事有点启发

**Comment by JIANG09** [comment]
这个动态的唱在静态的keynote上表现，有点难。或许我们可以想想别的，不要被陪孩子读诗的方式限制住了。

**Comment by soniclr** [comment]
春暖花开，江心湖畔，莲花朵朵，候鸟翩翩。
美景迷住了宝宝的双眼，他忍不住发出一声赞叹：“好美啊，老铁666”
此时，远处传来一阵孩儿般的轻声吟唱：泉眼无声惜细流，树阴照水爱晴柔。小荷才露尖尖角，早有蜻蜓立上头。
宝宝愣住，有点委屈，妈妈，那小姐姐唱的好美。
忍不住一声轻叹，奈何自己也不大会诗词，何况要教小孩呢。
只见那女娃娃跟随着大人走来，宝宝扑腾扑腾跑过去，姐姐，你唱的好好听，能教教我吗？
两小孩就欢快的去吟唱了。

大人席地而坐，攀谈。言罢，方知，小孩喜欢美妙的旋律，精准的音符，我们大人何尝不是如此呢。

他们向我们展示了《婷婷唱古诗》的节目，不同的古诗词，不同的节奏吟唱而出，朗朗上口，绕梁三日，不绝于耳。

宝宝自此回来后，每日都想听着词，唱着曲儿。 看到大白鹅会唱：鹅鹅鹅，曲项向天歌；吃饭后，会诵读“谁知盘中盘，粒粒皆辛苦”；看着春景图，会低吟“春去花还在，人来鸟不惊”……

家中无时不刻，都陪伴着《婷婷唱古诗》的声音，烟气萦绕，若古声古色……

**Comment by JIANG09** [comment]
# 初稿
**故事1 **：宝儿学校举行了歌咏大赛。宝儿献上自己的拿手曲目周杰伦的《双截棍》
“我拿根双截棍，哼哼哈尼～我拿根双截棍，哼哼哈你～”
看着宝儿在台上活蹦乱跳，台下的小朋友们拍手叫好，宝儿妈妈却有点担心。宝儿成天哼的都是这些流行乐曲，有写单调，有些苍白，总觉得缺了些什么。
音乐本来是美好的表达，好的音乐可以是一盏灯，指引人向上，向善，向美。可是，宝儿的音乐世界，却没有这些东西。

该怎么办呢？

**故事2**一天，宝儿妈妈带宝儿在小区里散步，听到一阵清脆的银铃般的歌声，原来是隔壁梅梅。梅梅银铃般吟唱着：落霞与孤鹜齐飞，秋水共长天一色。（可以换个别的）
宝儿妈先是一愣，唱的好美，歌美，词美，和天地融为一体。然后激动道：对，这就是我想要找的。用音乐，感知古诗词。音乐与诗歌的结合，太美了！

音乐可以是一盏灯，指引宝儿打开文化宝藏，那些堪称绝唱的古文（或古诗词），“青箬笠，绿蓑衣，斜风细雨不须归。”

“梅梅，这是谁教你的？”
“是手机上的婷婷老师，她每天都给我们唱歌！”

晚上，宝儿妈妈打开《婷婷唱古文》听了一首，《木兰辞》。

。。。。。。。。。占位符（还没写好，可以参照陪孩子读诗的对比方法，将流行歌词和古文的文字贴出来，插入音频）


故事3: 宝儿喜欢上了唱古文，还喜欢唱古诗，看到白云，看到落日、看到下雨，都会唱上一首。
全家人也喜欢上了婷婷唱古文，和宝儿一起唱，家里的文化氛围浓浓的。

除夕夜，家里团团圆圆，全家人一起唱《春节谣》，宝儿唱的最开心，我们笑的很开心。（keynote上放上《春节谣》的歌词和音频）

---
## 初稿感想
可以从别的角度切入，我选的是流行音乐和古诗词音乐的对比。因为我们的重点不完全是诗词，学诗，而是唱诗，所以强调音乐对诗词的指引作用会比较有针对性，也不容易和陪孩子读诗重合，音乐是我们的亮点，可以重点突出。

**Comment by Wenting11** [comment]
十二教练：（我把十二在微信上的建议贴在这里）
一个想法，那可不可以不要花那么多笔墨，说「我」为什么选择了这个产品。而是直接展示学习过程和学习后的变化，让观者直观感受到，你们在教什么，我们能得到什么？

前面的纠结都是呀…对产品本身的功能介绍反而很模糊。「宝儿喜欢上了唱古文，还喜欢作诗」像这句，喜欢唱诗↦作诗，出现得就很生硬，因为前面没有铺垫。

建议你们先给你们的产品认真画个像，说说它为什么值得被选择被购买，它到底用什么方法什么形式解决了用户的什么痛点。

嗯～还有个点，就是，你们有没有想过运用时空变形呢？比方说，假设这个产品普及，一百年后，这个世界会变得怎样？然后从100年后的那个时间点开篇。现在大家最小故事的叙事逻辑，跟「陪孩子读诗」是一样的，就比较难给人新鲜感。

**Comment by Wenting11** [comment]
- 面向的用户群：爸爸妈妈+孩子（我想孩子也会影响决策，主要是爸爸妈妈）
- 痛点：念诗枯燥，孩子不喜欢
- 婷婷唱古文：孩子天生喜欢音乐，喜欢有韵律的。婷婷唱古文通过唱，将诗歌和音乐结合。让孩子喜欢唱，不知不觉古诗词启蒙了。背后的认知科学规律是：我们人类喜欢音乐，也擅长记忆有韵律感的事物。
- 功能板块主要是两个：婷婷诗教板块，通过诗启发孩子感知生活观察世界；多才多艺板块，通过他们特殊的编曲，将诗和音乐一起启蒙。（唱贯穿始终，不管是哪个板块，都用到了他们通过编曲唱出来的古诗）
