### ISSUE TITLE
BP第四稿

### ISSUE THREAD

**Issue by Wenting11** [Wenting11/Tingting-sing-ancient-prose#8]
构想：置换身份，我们是婷婷团队，我们写一封信给有孩子的父母

小时候的梧桐树下，
你捧着书本，张口背着：

白日依山尽，
黄河入海流。
欲，欲，……

爸爸：欲，欲什么，这么简单的诗都背不下来。

那时候的你讨厌背诗，不知道背诗为了什么，为了考试，为了不被责骂吗？

长大的你，渐渐明白了诗的美好，它变成了你生命的一道印记。

考试失意时，你在笔记本上重重写下，「长风破浪会有时，直挂云帆济沧海」；
躺在草地上看着软软的白云，你会想起「天上有行云，人在行云里」
思念某个人时，你嘴里叨叨着「一种相思，两处闲愁，此情无计可消除，才下眉头却上心头」。
诗让你不孤独，内心不断的丰满……

时光匆匆，你成为了爸爸，孩子出生的那一刻，你泪流满面。
慢慢地，孩子牙牙学语了，孩子上蹿下跳了。你想着怎么让美好的诗词滋润孩子的心田。
你不想孩子像你小时候一样，枯燥地摇头换脑地背诗，那些个因为背不住诗被父亲责骂的时光偷偷爬到了你心上，泪水被眼眶使劲掬住。

拿着一本《给孩子的古诗词》，你蹲下身子，语调温和、满怀耐心、满脸希冀地给他念，可是他却一手打翻了书，跑开了。你们展开了艰苦卓绝的拉锯战，最后你被这个小小人儿打败了。
你也不敢把他丢到国学班，从早到晚，扯着嗓子诵读经典，害怕这样下去他会厌烦学习。
你为此苦恼着……

（这里换新一页keynote，音乐如果能和前面的基调不同更好）
婷婷愿做你的育儿小助手，孩子们的家庭教师。
婷婷不是诗歌的朗读者，也不是枯燥的讲述者。
婷婷是为孩子用心谱乐曲，把古诗词唱到孩子生命中的妈妈。试听一曲：（选一首）
婷婷是孩子们的家庭教师，用轻松有趣的方式，带孩子到广袤的诗词世界里去打滚。
婷婷诗教，为孩子的心灵送上书香早餐。

流光容易把人抛，
流传千古的诗词，
小时候的旋律，
会成为孩子耳朵里永远弥漫的书香

**Comment by Wenting11** [comment]
里面的爸爸也可以换成妈妈

**Comment by Wenting11** [comment]
十二：
还有两个问题，你们假设的BP受众是谁？想给ta传递什么信息呢？

**Comment by JIANG09** [comment]
# 修改版

小时候，教室里
你捧着书本，张口背着：

（选一首婷婷唱过的，最后讲产品时放同一首，前后呼应，突出效果）

老师说：欲，欲什么，讲了多少遍，还是记不住。


那时，你讨厌学古诗文，书本上的诗文，一篇篇面孔模糊，晦涩难懂。学这些，不就是为了考试，为了不被责骂吗？


后来，你成了大人，渐渐懂得了诗文的美。千年前的诗文，超越时空，陪伴你的身边。

人生失意，你在日记本上写下，「长风破浪会有时，直挂云帆济沧海」；
绿草茵茵，你躺着看着软软的白云，想起「天上有行云，人在行云里」
思念来袭，心中默念「一种相思，两处闲愁，此情无计可消除，才下眉头却上心头」
灵魂遇上诗文，不再孤独，不再浮躁，内心丰盈，思想厚重...


时光苒苒，你当了爸爸，孩子习字念书了，你思索：如何用诗文滋润孩子的心田？

拿着一本《给孩子的古诗词》，你语调温和、满怀耐心、满脸希冀，念给他听，可是他听着听着睡着了，或者自己跑开，玩去了。你想起了小时候，你拿着诗文读啊背啊，却觉枯燥无味；被责骂的时光爬上你的心头，那个怯怯的自己，苦恼的自己。你不想孩子也经历这些....  

婷婷用心为孩子谱乐曲，唱诗文。孩子的生命中，诗文不该是扭捏的字词，可以是流畅的音符，叩开孩子的心灵，滋养一个世界，这个世界，是美的世界。

美的世界是这样：（放一段山居，孩子唱的）
是这样：（放一段西江月，孩子唱的，因为如果有小孩唱出来，那说明这个产品是广受孩子喜欢的）


小时候的旋律，
会成为孩子耳朵边永远弥漫的书香 ，
婷婷唱古文，陪孩子读诗，陪孩子一同长大。

**Comment by Wenting11** [comment]
- 第一段用爸爸（妈妈）身份的考量是这样的，小的时候，是爸爸和孩子，长大了那一幕还是爸爸和孩子，只是第一幕中的你成了爸爸。这有一种情感的联结，和诗歌传承的感觉。

- 「时光匆匆，你成为了爸爸，孩子出生的那一刻，你泪流满面。」成为爸爸或者妈妈的那一刻，需要表现一下，但不等于需要用我的原话，只是不要淡化了。这是一种很特别的感受。我们有着对新生命对孩子本能的爱，所以育儿产品、母婴产品、儿童文学等关于儿童的会那么火，父母爱孩子，也许上一代的父母关心孩子的吃饱穿暖，这一代的父母很关注孩子的成长。

- 在想怎么让诗歌浸润孩子的心田的时候，就已经想起了小时候那种枯燥背诗的方式，自己不喜欢，还被父亲责骂。所以自己试着用陪孩子读诗的方式，拿着一本叶嘉莹的《给孩子的古诗词》，试着温柔耐心（不是以前父亲那种粗暴的方式）给孩子念，满怀希冀希望他会喜欢。但是相反孩子不感兴趣，跑开了。睡着的可能性比较小，因为孩子坐不住。除非是像凯叔讲故事那样讲了一段很长的故事后用比较平淡的语调念诗，帮助孩子入睡。

- 赞同首尾出现同一首歌，即童年时的诗歌和婷婷唱的诗歌形成对比。

- 赞同出现孩子的声音

- 「婷婷是孩子们的家庭教师，用轻松有趣的方式，带孩子到广袤的诗词世界里去打滚。」觉得关于教诗的部分也不能没有，就像十二教练说的，上一版视频就光听到唱了，没有说到教诗的。所以我觉得这个也得出现一下，婷婷诗教，通过轻松有趣的讲解方式，带孩子到广袤的诗词世界里去打滚。不需要详细介绍，只需要介绍有这么一个婷婷诗教。

**Comment by soniclr** [comment]
* 第一段老师批评的语气最好改改。—— 譬如，老师鼓励的说：欲，然后呢？加油。 可惜你还是背不下来。望着老师失望的摇摇头。你讨厌学古诗文，书本上的诗文…… 

* 首尾呼应和孩子的声音这是不错的。

* 诗教的内容不建议出现，只是在产品提及就好了，毕竟我们的 BP 主打就是唱古文。

* 诗文给现在长大后的你带来了什么益处，最好能提及下。硬生生的转过去说要指导小孩学诗，有点别扭。

* 最后诗教在歌曲中，好像《墨梅》有讲画面，可以在最后一起放出来，唱诗+画面描述，可以试着用这首

**Comment by Wenting11** [comment]
前面不是有一大段提到古诗词是潜移默化成为自己生命中的一道印记吗？

考试失意时，你在笔记本上重重写下，「长风破浪会有时，直挂云帆济沧海」；
躺在草地上看着软软的白云，你会想起「天上有行云，人在行云里」
思念某个人时，你嘴里叨叨着「一种相思，两处闲愁，此情无计可消除，才下眉头却上心头」。
诗让你不孤独，内心不断的丰满……


就是你小时候不懂，但长大就慢慢懂。但是不喜欢那种背诗的方式。
